name: The Amadis Project
favicon: null
layout_spectrum: 0.49638
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f3e6'
    - '#583b33'
    - '#817664'
    - '#acbe98'
    - '#909c83'
  brandStrength: 0.8268719520419836
  lightness: 0.3196783030871302
  saturation: 0.5
  rhythmicContrast: 0.8322189124301076
purpose: []
